<a href="https://colab.research.google.com/github/csanadferencz/CVSHomework/blob/master/EPLab2020_01d_PythonBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **EPLab 01d: Python Basics**
v2020.01


---

Version history:  
v2020.01 - initial version

---

### Using the Google Colab development environment

In order to participate in the course, you will need a Google account. We will be using the Google Drive and Google Colab web applications through a suitable browser (e.g. any modern version of Google Chrome or Mozilla Firefox).

Google Drive is a cloud-based storage facility where you can save all your work.

Google Colab gives you access to a cloud-based python development environment through notebooks. Notebooks are combined markdown + source code documents that enable formatted commenting, on-demand snippet execution by the interpreter, visualization, sharing and collaboration. Python notebook files have the extension .ipynb and are compatible with local notebook environments like IPythonNotebook and JupyterNotebook.

Every time you open a shared notebook during the course, you have to do the following steps before starting to work on it:
1. Download the notebook to your own Google Drive storage.
 - Click "Open in playground mode" (upper left taskbar)
 - Click "Save to Google Drive" (upper left taskbar)
 - Rename the notebook as you wish (upper left corner)
2. Connect to a "Python 3 (GPU)" runtime.
 - Click on the "Connect" button (upper right taskbar)
 - Wait until it connects (Allocating)
 - Hover over the RAM/Disk indicators (upper right taskbar): you should check that you got a Python 3 backend with GPU support
 - If your backend is not "Python 3 (GPU)", in the menu click "Runtime" then "Change runtime type" and select "Python 3" and "GPU"

Once you have done step 1,  you don't have to repeat it. Just open your copy of the Colab notebook from your own Google Drive storage (not the one I shared), and you are good to go. Just make sure you always connect to the correct runtime.

There is autosave but you can always click Ctrl+S to save your work.
You can use the mouse to click on the "run cell" icons (round play button) in the upper left corner of each code cell. Alternatively, you can use the Ctrl+Enter (and Shift+Enter) key combinations for running the cell (and selecting the next cell).

### Python basics
Trying the sample code snippets below should be enough to get you through the lab. This is not a programming course but you have to be able to
- perform basic math operations with literals and variables,
- understand basic control flow (if, for statements),
- define functions,
- manipulate numpy matrices and
- print or visualize their content.

If you need further material, visit: https://docs.python.org/3/tutorial/index.html

In [ ]:
3

3

In [ ]:
# This is a line comment.
"""
And this is
a block comment.
"""
a = 3  # assignment, not equality!
b = a + 2
print(1)
print(a**0)  # power notation of x to the power of y: x**y
print(1+1)
print(a)
print(b)
print(a+b)
print('Guess the next number!')

1
1
2
3
5
8
Guess the next number!


In [ ]:
a = b + a+b  # reassign variable a
print(f'The next number is {a}. This seems like a Fibonacci sequence!')  # note f'' syntax for formatted strings

The next number is 13. This seems like a Fibonacci sequence!


In [ ]:
print(f'Let\'s do sequences with lists.')
c = [1,1,2,3,5,8,13,21,34,55]
print(f'Simple fib: {c}')
print(f'Python indexing is done with square brackets and starts with 0: {c[0]}. Element at idx 5: {c[5]}. '\
      f'Last element: {c[-1]}. Next to last element: {c[-2]}.')  # note the line break in the code
d = range(10)
print(f'Nums up to 10: {d}')
print(f'Type of d is: {type(d)}')
d_list = list(d)
print(f'We need d as a {type(d_list)}: {d_list}.')

Let's do sequences with lists.
Simple fib: [1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
Python indexing is done with square brackets and starts with 0: 1. Element at idx 5: 8. Last element: 55. Next to last element: 34.
Nums up to 10: range(0, 10)
Type of d is: <class 'range'>
We need d as a <class 'list'>: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9].


In [ ]:
# Let's learn the for loop
e = []
print(e)
e.append(1)
e.append(1)
print(e)
print(len(e))

for i in range(2, 20):
    e.append(e[i-1] + e[i-2])  # Python is indentation-aware! use Tab key!

print(e)
ee = enumerate(e)
print(ee)
lee = list(ee)
print(lee)
print(type(lee[15])) # a tuple is like a fixed-length immutable list.
print(lee[15])

[]
[1, 1]
2
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765]
[(0, 1), (1, 1), (2, 2), (3, 3), (4, 5), (5, 8), (6, 13), (7, 21), (8, 34), (9, 55), (10, 89), (11, 144), (12, 233), (13, 377), (14, 610), (15, 987), (16, 1597), (17, 2584), (18, 4181), (19, 6765)]
<class 'tuple'>
(15, 987)


In [ ]:
# define a function you will reuse
def fibgen(n=10):  # if not specified otherwise, default value for argument n is 10
    result = [1,1]
    for i in range(2,n):
        result.append(result[i-1] + result[i-2])
    return result

In [ ]:
fibs = fibgen()    # invoke your function
print(fibs)
fibs = fibgen(33)  # invoke your function again
print(fibs)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393, 196418, 317811, 514229, 832040, 1346269, 2178309, 3524578]


In [ ]:
print(a==999) # note == is equality, not assignment!

for i, fib in enumerate(fibs):  # for each tuple (i, fib)
    if i%2 == 0:  # if index is even (divisible by 2) (note modulo operator is %)
        print(f'{i+1:02d}-th Fibonacci number is: {fib:7d}')  # note the formatting tricks. read manual for more.

False
01-th Fibonacci number is:       1
03-th Fibonacci number is:       2
05-th Fibonacci number is:       5
07-th Fibonacci number is:      13
09-th Fibonacci number is:      34
11-th Fibonacci number is:      89
13-th Fibonacci number is:     233
15-th Fibonacci number is:     610
17-th Fibonacci number is:    1597
19-th Fibonacci number is:    4181
21-th Fibonacci number is:   10946
23-th Fibonacci number is:   28657
25-th Fibonacci number is:   75025
27-th Fibonacci number is:  196418
29-th Fibonacci number is:  514229
31-th Fibonacci number is: 1346269
33-th Fibonacci number is: 3524578


In [ ]:
import sys
sys.version_info

sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)

### Learn Numpy
Numpy is the best n-dimensional general-purpose linear algebra library for Python. It is convenient, fast (implemented in C and compiled to native), well-supported, and everyone uses it.

In [ ]:
# let's import numpy in order to be able to use it
import numpy as np

f = np.array(e)
print(type(f))
print(f)
print(f.shape)  # if a tuple is one long, we put the comma in the end
print(f[5])
print(f[[5,15]])
print(f[[5]])

<class 'numpy.ndarray'>
[   1    1    2    3    5    8   13   21   34   55   89  144  233  377
  610  987 1597 2584 4181 6765]
(20,)
8
[  8 987]
[8]


In [ ]:
g = np.array([[1,2,3],
              [4,5,6]])
print(type(g))
print(g)
print(g.shape)
print('Some indexing...')
print(g[1,0])
print(g[0,2])
print(g[1])
print(g[1,:])
print(g[1,1:])
print(g[1,:2])
print(g[:,1])
print('More indexing...')
print(g[:,[1,2]])
print(g[:,[1]])

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
(2, 3)
Some indexing...
4
3
[4 5 6]
[4 5 6]
[5 6]
[4 5]
[2 5]
More indexing...
[[2 3]
 [5 6]]
[[2]
 [5]]


In [ ]:
# Numpy broadcasting
print(2*g)
print()

h1 = np.array([[10, 20, 30]])
h2 = np.array([[100], [200]])
print(h1)
print(h2)
print()

print(g+h1)
print(g+h2)

[[ 2  4  6]
 [ 8 10 12]]

[[10 20 30]]
[[100]
 [200]]

[[11 22 33]
 [14 25 36]]
[[101 102 103]
 [204 205 206]]


In [ ]:
# and of course, the dot product:
print(h1)
v = np.array([[1,2,3]]).T  # T for transpose
print(v)
print()

print(np.dot(h1, v))
print(np.dot(v, h1))

[[10 20 30]]
[[1]
 [2]
 [3]]

[[140]]
[[10 20 30]
 [20 40 60]
 [30 60 90]]


### COVID calculator
Let's do something useful with python.

In [ ]:
def ppv(sensitivity=1.0, specificity=1.0, prevalence=0.01, verbose=False):
    result = sensitivity*prevalence / (sensitivity*prevalence + (1-specificity)*(1-prevalence))
    if verbose:
        print(f"Positive result means {100*result:6.2f}% chance of infection     @ {printperf(sensitivity, specificity, prevalence)}")
    return result

def npv(sensitivity=1.0, specificity=1.0, prevalence=0.01, verbose=False):
    result = specificity*(1-prevalence) / (specificity*(1-prevalence) + (1-sensitivity)*prevalence)
    if verbose:
        print(f"Negative result means {100*result:6.2f}% chance of being healthy @ {printperf(sensitivity, specificity, prevalence)}")
    return result

def printperf(sensitivity, specificity, prevalence):
    return f"[SNS={100*sensitivity:6.2f}%; SPC={100*specificity:6.2f}%; R={100*prevalence:6.2f}%]"

In [ ]:
sns = 0.99
spc = 0.96
r = 0.001

_ = ppv(sns, spc, r, verbose=True)
_ = npv(sns, spc, r, verbose=True)

Positive result means   2.42% chance of infection     @ [SNS= 99.00%; SPC= 96.00%; R=  0.10%]
Negative result means 100.00% chance of being healthy @ [SNS= 99.00%; SPC= 96.00%; R=  0.10%]


This is enough for preparation! You will learn some further tricks (e.g. graphical visualization) during the lab session.